### ISSUE TITLE
sell bug and essentials worth price not working

### ISSUE THREAD

**Issue by PortGasMC** [mastercake10/uShop#8]
when you sell items without price and you click the botton to sell it , it will take away the item and will not give it back.

also essentials worth in the config file doesnt work, pls update the plugin 

regards
port

**Comment by mastercake10** [comment]
This does not make any sense to me. I mean if you're about to sell an item in real life for $0, you're supposed to give that item to this person.

Anyways, I do understand that people are selling accidentally items that are zero worth, so this would be a feature request.

Please provide more information on your essentials issue, for example, essential version, server version, plugin version and create a new issue for it. I'll close this for now since you're not meant to create one issue for two topics.
